# Generated by Django 5.1.7 on 2025-07-15 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50)),
                ('brand', models.CharField(choices=[('CHREVROLET', 'CHREVROLET'), ('FORD', 'FORD'), ('NISSAN', 'NISSAN'), ('CITROEN', 'CITROEN')], max_length=20)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
