# Generated by Django 5.1.7 on 2025-07-15 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='brand',
            field=models.CharField(choices=[('CHEVROLET', 'CHEVROLET'), ('FORD', 'FORD'), ('NISSAN', 'NISSAN'), ('CITROEN', 'CITROEN')], max_length=20),
        ),
    ]
