# Generated by Django 5.2.4 on 2025-07-17 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_cars_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='brand',
            field=models.CharField(choices=[('CHEVROLET', 'CHEVROLET'), ('FORD', 'FORD'), ('NISSAN', 'NISSAN'), ('CITROEN', 'CITROEN')], default='Chevrolet', max_length=20),
        ),
    ]
